config/routes.rb
Rails.application.routes.draw do
  resources :event_dishes
  resources :user_dishes
  resources :user_allergies
  resources :events
  resources :dishes
  resources :allergies
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/allergy.rb
class Allergy < ApplicationRecord
    has_many :user_allergies
    has_many :users, through: :user_allergies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :dishes
    has_many :users, through: :dishes
    has_many :allergies, through: :users

    validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_allergies
    has_many :allergies, through: :user_allergies
    has_many :dishes
    has_many :events, through: :dishes
end

app/models/user_allergy.rb
class UserAllergy < ApplicationRecord
    belongs_to :user
    belongs_to :allergy
end

app/controllers/allergies_controller.rb
class AllergiesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
        @events = Event.all
    end

    def show
        @event = Event.find(params[:id])
        @user = User.new
        @users = User.all
    end

    def new
        @event = Event.new
    end

    def create
        event = Event.create(events_params)
        if event.valid?
            redirect_to event
        else
            redirect_to new_event_path
        end 
    end

    private

        def events_params
            params.require(:event).permit(:name, :date)
        end
end

app/controllers/user_allergies_controller.rb
class UserAllergiesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    def show
        @user = User.find(params[:id])
    end
    def create
        user = User.create(user_params)
        if user.valid?
            redirect_to user
        else
            redirect_to users_path
        end
    end

    private
        def user_params
            params.require(:user).permit(:first_name, :last_name, :event_id])
        end
end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/event_dishes_helper.rb
module EventDishesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_allergies_helper.rb
module UserAllergiesHelper
end

app/helpers/user_dishes_helper.rb
module UserDishesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All Events:</h1>

<ul>
    <% @events.each do |ev| %>
        <li>
            <%= link_to ev.name, ev %>
        </li>
    <% end %>
</ul>
<br><br><br><br>
<%= link_to "Create Your Own Event >", new_event_path %>

app/views/events/new.html.erb
<h1>Create a New Event:</h1>

<%= form_for @event do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>

    <%= f.label :date %>
    <%= f.date_field :date %><br><br>

    <%= f.submit %>
<% end %>

<br><br><br><br>
<%= link_to "< Cancel", events_path %>

app/views/events/show.html.erb
<h1> <%= @event.name %> </h1>

<h3>Attendees:</h3>
<ul>
    <% @event.users.each do |user| %>
        <li>
            <%= link_to user.first_name + ' ' + user.last_name, user %>
        </li>
    <% end %>
</ul>

<h3>Allergens:</h3>
<ul>
    <% @event.allergies.uniq.each do |allergy| %>
        <li>
            <%= allergy.name %>
        </li>
    <% end %>
</ul>

<h3>Dishes Available:</h3>
<ul>
    <% @event.dishes.each do |dish| %>
        <li>
            <%= link_to dish.name, dish %>
        </li>
    <% end %>
</ul>
<br><br><br><br>

<h4>Join the Party</h4>

<%= form_for @user do |f| %>
    <h5>Create a Profile or Select from Existing:</h5>
    <%= f.hidden_field :event_id, :value => @event.id %>
    <%= f.collection_select :id, @users, :id, :last_name, {:include_blank => 'Select User'} %><br><br>
    
    <%= f.label :first_name %>: <%= f.text_field :first_name %><br><br>
    <%= f.label :last_name %>: <%= f.text_field :last_name %><br><br>

    <%= f.submit %>

<% end %>

<br><br><br><br>
<%= link_to "< All Events", events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssociationTesting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>All Users</h1>
<ul>
    <% @users.each do |user| %>
        <li>
            <%= link_to user.first_name + ' ' + user.last_name, user%>
        </li>
    <% end %>
</ul>

app/views/users/show.html.erb
<h1> <%= @user.first_name + ' ' + @user.last_name %> </h1>

<h3>Allergens:</h3>
<ul>
    <% @user.allergies.each do |al| %>
        <li>
            <b><%= al.name %>:</b> <%= al.specifics %>
        </li>
    <% end %>
</ul>

<br><br>

<h3>Food they’ve made:</h3>
<ul>
    <% @user.dishes.each do |dish| %>
        <li>
            Event: <%= link_to dish.event.name, dish.event %><br>
            <%= dish.name %> | <%= dish.details %>
        </li>
    <% end %>
</ul>

<br><br>

<h3>Parties they've attended:</h3>
<ul>
    <% @user.events.uniq.each do |event| %>
        <li>
            <%= link_to event.name, event %> | <%= event.date %>
        </li>
    <% end %>
</ul>
<br><br><br><br><br><br>
<%= link_to "< Home", users_path %>